# config.yml
settings:
  max-mules-per-player: 5
  level-up-messages: true
  auto-save-interval: 5 # minutes

mule-settings:
  base-health: 20.0
  base-speed: 0.2
  base-jump-strength: 0.5
  experience-multiplier: 1.0